version: "3.5"
services:
    web:
        image: "redis1:latest"
        ports:
            - "80:5000"
        volumes:
            - .:/code
        environment:
            FLASK_ENV: development
        depends_on:
            - redis
    redis:
        image: "redis:alpine"
        volumes:
            - type: "volume"
              source: "mydata"
              target: "/data"
        deploy:
            resources:
                limits:
                    cpus: '0.50'
                    memory: 50M
                reservations:
                    cpus: '0.25'
                    memory: 20M
        healthcheck:
            test: redis-cli ping
            interval: 60s
            retries: 5
            start_period: 20s
            timeout: 10s
volumes:
    mydata:
